### PR TITLE
Implement remove & list features

### PR DESCRIPTION
**Pull request by creekorful**
Closes: #5
Closes: #30

### CODE REVIEW

**Comment by creekorful** [comment]
Hello @go-pkg-org/core-maintainers, this PR should implements features to remove installed packages as well as list them.

I have moved the configuration part into a new config package to re-use it. 
This could be helpful when we will implement config file (#34)

**Comment by creekorful** [comment]
I will implement #30 with it before marking it available for renew

**Review by Johannestegner — APPROVED** [review]
From what I can see, it looks good. I'm extremely tired though, So I'd very much want @frozzare to take a peak too :)

**Review by frozzare — APPROVED** [review]
Looks good to me! Just a note about that we need to think a bit of how the config functions will work with the config file later, but that's something we will take in #34, better to merge this now and then work more on the configuration file after.

**Pull request merged**
